
export default {
    name: 'Text2Dia',
    description: 'Convert text / code to diagrams and diagrams back to text. Supports **Math (tex), Mermaid, PlantUML** etc.',
    settings: [],
    version: '1.0.5',
    icon: 'sync_alt',
    instructions: `
This plugin allows users to easily convert text to diagrams and diagrams back to text. It supports various diagram types including **Math (tex)**, **Mermaid**, **PlantUML**, **Graphviz**, etc.

To convert text to diagrams, select the "Convert to Dia" menu after selecting some text:

![](https://images.amplenote.com/9a2a74f4-03a7-11ee-b968-8e37e8b27b1d/4c103c2e-c806-41f3-b410-121c9829e864.gif)

To convert diagram back to text, use the "Convert to Text" menu:

![](https://images.amplenote.com/9a2a74f4-03a7-11ee-b968-8e37e8b27b1d/8d4d3121-7c3c-4039-a1f0-2b3e94b8fa10.gif)

The plugin also has [tight integration for math](https://public.amplenote.com/NzF1LJXnPUBHZc9sqRKmkiRn). You can also [create diagram using an \`{expression}\`](https://public.amplenote.com/48taAYoWNbPwpsnR668hXkt3).
`.trim().replaceAll('\n', '<br />'),
    template: `
### Code
<<Code>>


### Changelog
13/07/2024 - Temporarily fixed issue with replaceSelection
28/09/2024 - Reduced bundle size
13/10/2024 - Fixed issue with replaceSelection
---
*Note:* *The images are generated by the free and open source service* [*kroki.io*](https://kroki.io)*.*

`.trim()
};